/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32Cube for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdint.h>
#include <stdbool.h>
#include <stm32h533xx.h>
#include "plib.h"
#include "plib_config.h"

unsigned long int ticks = 0;

int main(void)
{
    pl_init();

	int elapsed = 0;
	pl_screen_set(1);

	while (1) {
		pl_do();
		// pl_board_led_set(1);
		// // GPIOA->BSRR = (1 << 5); // Bit set reset register
		// for (int i = 0; i < 1000000; i++) {
		// 	__NOP();
		// }

		// pl_board_led_set(0);
		// // GPIOA->BRR = (1 << 5); // Bit reset register
		// for (int i = 0; i < 1000000; i++) {
		// 	__NOP();
		// }

		// int pressed = pl_board_button_get();
		
		// if (pressed) {
		// 	double elapsed = (double) ticks / PL_TICKS_PER_SECOND;
		// 	__NOP();

		// }
		// pl_board_led_set(pressed);

		int new_elapsed = ticks / PL_TICKS_PER_SECOND;
		bool is_on = (new_elapsed % 2) == 0;

		if (new_elapsed != elapsed) {
			elapsed = new_elapsed;
			pl_log("1 second more elapsed");
		}

		pl_board_led_set(is_on);
		pl_led_set(is_on);

	}
}

void SysTick_Handler(void) {
	ticks++;
}
