/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32Cube for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdint.h>
#include <stdbool.h>
#include <stm32h533xx.h>
#include "plib.h"
#include "plib_config.h"

#define DIGIT_0 0x3F
#define DIGIT_1 0x06
#define DIGIT_2 0x5B
#define DIGIT_3 0x4F
#define DIGIT_4 0x66
#define DIGIT_5 0x6D
#define DIGIT_6 0x7D
#define DIGIT_7 0x07
#define DIGIT_8 0x7F
#define DIGIT_9 0x6F


unsigned long int ticks = 0;

#include <stdint.h>

uint32_t calc_display(uint8_t hour, uint8_t minute) {
	
	const uint8_t digits[] = {DIGIT_0, DIGIT_1, DIGIT_2, DIGIT_3, DIGIT_4, DIGIT_5, DIGIT_6, DIGIT_7, DIGIT_8, DIGIT_9};

	uint8_t minutes_one = 0;
	uint8_t minutes_ten = 0;
	uint8_t hours_one = 0;
	uint8_t hours_ten = 0;

	minutes_one = digits[minute % 10];
	minutes_ten = digits[minute / 10];
	hours_one = digits[hour % 10];
	hours_ten = digits[hour / 10];

	// blinking points
	minutes_ten |= (1 << 7); 

		

	// 32 Bit = 4 Byte --> hours_ten shifted to Byte 3, hours_one shifted to Byte 2, ....
	uint32_t displayTime = (hours_ten << 24) | (hours_one << 16) | (minutes_ten << 8) | minutes_one;

	return displayTime;
}

int main(void)
{
    pl_init();
	pl_screen_set(1);


	int seconds_elapsed = 0;
	int minutes_elapsed = 0;
	int hours_elapsed = 0;

	while (1) {
		pl_do();

		int new_seconds_elapsed = ticks / PL_TICKS_PER_SECOND;


		if (new_seconds_elapsed != seconds_elapsed) {
			seconds_elapsed = new_seconds_elapsed;

			if (seconds_elapsed >= 60) {
				seconds_elapsed = 0;
				minutes_elapsed++;
			}
			if (minutes_elapsed >= 60) {
				minutes_elapsed = 0;
				hours_elapsed++;
			}
			if (hours_elapsed >= 24) {
				hours_elapsed = 0;
			}

			uint32_t displayTime = calc_display(hours_elapsed, minutes_elapsed);

			pl_alarmclock_display(displayTime);
		}
	}
}

void SysTick_Handler(void) {
	ticks++;
}
